apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tca-db.fullname" . }}-connectivity
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "tca-db.name" . }}
    chart: {{ include "tca-db.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: l4dbadmin-ui
type: Opaque
data:
  PGRST_DB_URI: {{ printf "postgres://tca:tca@%s-postgresql.%s/tca" .Release.Name .Release.Namespace   | b64enc | quote }}
  BMLLX_DATABASE_URL: {{ printf "postgres://tca:tca@%s-postgresql.%s/tca" .Release.Name .Release.Namespace   | b64enc | quote }}
