{{- if .Values.dbadminui.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tca-db.fullname" . }}-l4dbadmin-ui
  labels:
    app: {{ include "tca-db.name" . }}
    chart: {{ include "tca-db.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: l4dbadmin-ui
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "tca-db.name" . }}
    release: {{ .Release.Name }}
    component: l4dbadmin-ui
{{- end }}

# availabe internally for debug purpose ?
