apiVersion: v1
kind: Service
metadata:
  name: {{ include "tca-db.fullname" . }}-postgrest
  labels:
    app: {{ include "tca-db.name" . }}
    chart: {{ include "tca-db.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: postgrest
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "tca-db.name" . }}
    release: {{ .Release.Name }}
    component: postgrest
